In [ ]:
# =================================================================
#       Numpy Introduction
#==================================================================

In [2]:
import numpy as np

In [4]:
a = np.array([1, 3, 4])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 3 4]


In [8]:
b = np.array([[1, 2, 3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [10]:
# Get Shape
a.shape

(3,)

In [11]:
b.shape

(2, 3)

In [12]:
# Get dimension
a.ndim

1

In [13]:
b.ndim

2

In [15]:
# Get type
a.dtype

dtype('int64')

In [17]:
m = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(m)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
# Get a specif element [r, c]
m[1, -2]

np.int64(13)

In [22]:
# Get a specific row
m[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [24]:
# Get a specific column
m[:,2]

array([ 3, 10])

In [27]:
# Getting a little more fancy [startindex : endindex:stepsize]
m[0, 1:-1:2]

array([2, 4, 6])

In [28]:
# modifying array
m[1,5] = 20
print(m)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [29]:
m[:,2] = [1,2]
print(m)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [ ]:
# * 3-d example

In [31]:
n =  np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(n)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
