In [ ]:
# ================================================ 
#             different types of arrays
# ================================================

In [4]:
import numpy as np

In [5]:
# ALL 0's matrix
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# All 1'S matrix

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
# Any other number np.full((shape),(number))
np.full((2,2), 15)

array([[15, 15],
       [15, 15]])

In [16]:
np.full((2,2), 21, dtype = 'float32')

array([[21., 21.],
       [21., 21.]], dtype=float32)

In [ ]:
# Random numbers

In [20]:
np.random.randint(8)

7

In [21]:
np.random.randint(7, size = (3,3))

array([[3, 3, 6],
       [4, 1, 0],
       [1, 2, 5]], dtype=int32)

In [23]:
# identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
# Repeating an array
arr = np.array([[1,2,3]])
rl = np.repeat(arr,3, axis = 0)
print(rl)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
