In [2]:
import numpy as np

In [5]:
# creating array
subjects = ["Maths", "Science", "English"]
std_marks = np.array([
    [78, 85, 90],
    [67, 77, 82],
    [90, 91, 89],
    [56, 65, 70],
    [88, 79, 92]  
])

print("Subjects:",subjects)
print("Student_marks:", std_marks)

Subjects: ['Maths', 'Science', 'English']
Student_marks: [[78 85 90]
 [67 77 82]
 [90 91 89]
 [56 65 70]
 [88 79 92]]


In [9]:
shape = std_marks.shape
print("Shape of the table :", shape)

Shape of the table : (5, 3)


In [10]:
d_type = std_marks.dtype
print("Data type:", d_type)

Data type: int64


In [16]:
table_dimension = std_marks.ndim
print(f"Dimesion of the table: {table_dimension} dimension")

Dimesion of the table: 2 dimension


In [22]:
# accessing student1 maaths marks
math_marks = std_marks[0,0]
print("1st student Maths marks :",math_marks)

#accessing science marks of the 3rd student
s_mrks = std_marks[2,1]
print("3rd student science marks:", s_mrks)

#accessing english marks of the 5th student
e_marks = std_marks[4,2]
print("5th student english marks:", e_marks)

1st student Maths marks : 78
3rd student science marks: 91
5th student english marks: 92


In [24]:
#Accessing all subjects marks of all the student

maths_marks = std_marks[:,0]
science_marks = std_marks[:,1]
english_marks = std_marks[:,2]

print("Maths marks:")
print(maths_marks)

print("Science_marks")
print(science_marks)

print("English marks:")
print(english_marks)


Maths marks:
[78 67 90 56 88]
Science_marks
[85 77 91 65 79]
English marks:
[90 82 89 70 92]


In [26]:
# Change student 4 English marks to 75
print("array before modification:", std_marks)
std_marks[4,2] = 75
print("array after modification", std_marks)

array before modification: [[78 85 90]
 [67 77 82]
 [90 91 89]
 [56 65 75]
 [88 79 92]]
array after modification [[78 85 90]
 [67 77 82]
 [90 91 89]
 [56 65 75]
 [88 79 75]]


In [27]:
# Change student 2 math to 70
# Change student 5 science to 80

print("array before modification:", std_marks)
std_marks[1,0] = 70
std_marks[4,1] = 75
print("array after modification", std_marks)

array before modification: [[78 85 90]
 [67 77 82]
 [90 91 89]
 [56 65 75]
 [88 79 75]]
array after modification [[78 85 90]
 [70 77 82]
 [90 91 89]
 [56 65 75]
 [88 75 75]]


In [29]:
# Add 5 marks to all
print("array before adding 5 marks:")
print(std_marks)

std_marks = std_marks + 5
print("array after adding 5 marks:")
print(std_marks)

array before adding 5 marks:
[[83 90 95]
 [75 82 87]
 [95 96 94]
 [61 70 80]
 [93 80 80]]
array after adding 5 marks:
[[ 88  95 100]
 [ 80  87  92]
 [100 101  99]
 [ 66  75  85]
 [ 98  85  85]]


In [33]:
# Find average marks

avg_marks = std_marks.mean()
print(round(avg_marks))

89


In [35]:
# Find max
# Find min
# Find sum

max_marks = std_marks.max()
print("Maximun marks:")
print(max_marks)

min_marks = std_marks.min()
print("Minimun marks")
print(min_marks)

total_marks = std_marks.sum()
print("Total marks")
print(total_marks)

Maximun marks:
101
Minimun marks
66
Total marks
1336


In [6]:
#creating arrays with zeros
data = np.zeros(3)
print(data)

[0. 0. 0.]


In [8]:
data1 = np.zeros([5,3])
print(data1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
# Create array of 4 rows, 2 columns (with 0's)
zero_array = np.zeros([2,4])
print(zero_array)

print("----------------")
# Create array of 3 rows, 5 columns
z_arr = np.zeros([5,3])
print(z_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
----------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
#creating ones
data_1s = np.ones([3,3])
print(data_1s)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
# Create 6×2 array (1s)
abc = np.ones([6,2])
print(abc)

print("-----------------")
# Create 2×4 array
dce = np.ones([2,4])
print(dce)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
-----------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [26]:
# np.arange() → Real world numbers
#Create 1-20
numbers_1 = np.arange(1,21)
print(numbers_1)

numbers_2 = np.arange(100,201,10)
print("numbers 100-200 step 10:")
print(numbers_2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
numbers 100-200 step 10:
[100 110 120 130 140 150 160 170 180 190 200]


In [35]:
# Random Data (Real Data Analytics usage)
# 10 students, 4 subjectas
random_numbers = np.random.randint(0,100,(10,4))
print("student marks:", end= "\n")
print(random_numbers)

student marks:
[[74 48 86 14]
 [23 10 42 88]
 [30 94 81 70]
 [44 12 42 41]
 [84 40 35 33]
 [90 80 37 48]
 [87 99 14 56]
 [46 27 44 23]
 [14 59 90 45]
 [44 25 76 48]]


In [36]:
# Random float data
ranodm_float = np.random.rand(5,3)
print(ranodm_float)

[[0.37142485 0.74801195 0.17881873]
 [0.03734424 0.58007157 0.52915803]
 [0.37495714 0.21851981 0.40751863]
 [0.76021338 0.76447564 0.65006108]
 [0.91870687 0.69962687 0.97778857]]


<!-- Create dataset:

8 employees
3 months salary
salary between 20000–50000

Do:

✅ create array 
✅ check shape
✅ check dtype
✅ get row 3
✅ get column 2
✅ modify one value
✅ find max
✅ find mean -->

emp_salary = np.random.randint(20000,50001,(8,3))
print(emp_salary)

In [52]:
emp_salary = np.random.randint(20000,50001,(8,3))
print(emp_salary)

[[33195 48406 32760]
 [48715 37314 27055]
 [24044 48401 27458]
 [35295 37165 41832]
 [26217 21183 29696]
 [24164 24071 47041]
 [24256 24775 39223]
 [45716 48423 41895]]


In [62]:
# Create dataset:

# 8 employees
# 3 months salary
# salary between 20000–50000

print("Shape of the array is:", np.shape(emp_salary))
print("Dimesion of array is:", np.ndim(emp_salary))
print("Data type", emp_salary.dtype)

print("row3:")
print(emp_salary[2])

print("Column2")
print(emp_salary[:,2])

emp_salary[0,2] = 45000
print("Array after modification:")
print(emp_salary)

print("Maximun salary:")
print(emp_salary.max())

print("Minimun Salary:")
print(emp_salary.min())

print("Average salary:")
avg = emp_salary.mean()
print(round(avg))

Shape of the array is: (8, 3)
Dimesion of array is: 2
Data type int32
row3:
[24044 48401 27458]
Column2
[45000 27055 27458 41832 29696 47041 39223 41895]
Array after modification:
[[33195 48406 45000]
 [48715 37314 27055]
 [24044 48401 27458]
 [35295 37165 41832]
 [26217 21183 29696]
 [24164 24071 47041]
 [24256 24775 39223]
 [45716 48423 41895]]
Maximun salary:
48715
Minimun Salary:
21183
Average salary:
35439
