In [ ]:
# **************************************
# Dataset 1 — Sales Data (E-commerce)
# **************************************

In [19]:
import numpy as np

sales = np.array([
    [101, 500, 10],
    [102, 300, 5],
    [103, 700, 8],
    [104, 200, 20],
    [105, 1000, 2]
])

In [4]:
# Task 1: Basic Info
# Find shape
# Find dtype
# Number of products?

In [5]:
print("Sahpe of the array:",sales.shape)
print("Data type:", sales.dtype)
print("Number of producs", len(sales))

Sahpe of the array: (5, 3)
Data type: int64
Number of producs 5


In [6]:
# Task 2: Revenue Calculation

# Revenue = Price × Quantity
# Create new array for revenue
# Print revenue for each product

In [8]:
for i in range(len(sales)):
    print(f"product_id: {sales[i][0]} Revenue: {sales[i][1]*sales[i][2]}")

product_id: 101 Revenue: 5000
product_id: 102 Revenue: 1500
product_id: 103 Revenue: 5600
product_id: 104 Revenue: 4000
product_id: 105 Revenue: 2000


In [ ]:
# Task 3: Total Business Revenue
# Find total revenue using NumPy

In [7]:
Revenue_sales = np.array(sales[:,1]*sales[:,2])
total_revenue = Revenue_sales.sum()
print("Total Revenue = ",total_revenue)

Total Revenue =  18100


In [ ]:
# Task 4: Highest Selling Product
# Find product with highest quantity sold

In [10]:
for i in range(len(sales)):
    if sales[i][2] == sales[:,2].max():
        high_qty = sales[i][0]
        print(f"Highest Quantity product= {high_qty} and Qty = {sales[:,2].max()}")

Highest Quantity product= 104 and Qty = 20


In [ ]:
# Task 5: Increase Price
# Increase all prices by 10%

In [12]:
price_before_incresing = sales[:,1]
print("Product price:",price_before_incresing)

price_after_increasing = sales[:,1]+sales[:,1]*(10/100)
print("Price after increasing 10%:", price_after_increasing)

Product price: [ 500  300  700  200 1000]
Price after increasing 10%: [ 550.  330.  770.  220. 1100.]


In [ ]:
# Task 6: Add New Product
# [106, 400, 15]

In [26]:
new_product = np.array([[106, 400, 15]])
sales = np.append(sales, new_product, axis=0)
print(sales)
print(sales.shape)

[[ 101  500   10]
 [ 102  300    5]
 [ 103  700    8]
 [ 104  200   20]
 [ 105 1000    2]
 [ 106  400   15]
 [ 106  400   15]]
(7, 3)


In [ ]:
# **************************************
#   Dataset 1 — Sales Data (E-commerce)
# **************************************

In [27]:
columns = ["Emp_ID", "Salary", "Experience"]

In [28]:
emp = np.array([
    [1, 25000, 1],
    [2, 40000, 3],
    [3, 60000, 5],
    [4, 30000, 2],
    [5, 80000, 7]
])

In [ ]:
# Task 1: Average Salary
# Find average salary

In [29]:
avg_salary = emp[:,1].mean()
print("Average Salary:", avg_salary)

Average Salary: 47000.0


In [30]:
# Task 2: Highest Salary
# Find max salary

In [31]:
Highest_sal = emp.max()
print("Highest Salary:", Highest_sal)

Highest Salary: 80000


In [ ]:
# Task 3: Salary Increment
# Increase all salaries by 5000

In [34]:
sal_before_inc = emp[:,1]
print("Salary before increment:", sal_before_inc)

emp[:,1] = emp[:,1] + 5000
print("Salary after increment", emp[:,1])

print(emp)

Salary before increment: [30000 45000 65000 35000 85000]
Salary after increment [35000 50000 70000 40000 90000]
[[    1 35000     1]
 [    2 50000     3]
 [    3 70000     5]
 [    4 40000     2]
 [    5 90000     7]]


In [40]:
# Task 4: Create New Employees (using random)
# 3 employees
# salary between 20000–70000

In [52]:
new_emp_id = np.arange(6,9).reshape(3,1)
new_emp_sal = np.random.randint(20000, 70000,(3,1))
new_experience = np.random.randint(2,6,(3,1))

new_emp = np.hstack((new_emp_id, new_emp_sal, new_experience))
emp = np.append(emp, new_emp, axis=0)
print(emp)
emp.shape


[[    1 35000     1]
 [    2 50000     3]
 [    3 70000     5]
 [    4 40000     2]
 [    5 90000     7]
 [    6 67385     5]
 [    7 36465     4]
 [    8 29132     2]
 [    6 66391     5]
 [    7 52470     4]
 [    8 21065     3]]


(11, 3)

In [ ]:
# **********************************
#  Dataset 3 — Student Performance
# **********************************

In [53]:
subjects = ["Math", "Science", "English"]

In [54]:
marks = np.random.randint(30, 100,(6,3))

In [ ]:
# Task 1:
# Print dataset
# Find average marks

In [60]:
print("Marks data:")
print(marks)

print("Average marks =", round(marks.mean()))

Marks data:
[[85 76 95]
 [82 88 58]
 [71 67 43]
 [67 35 72]
 [35 67 43]
 [37 99 76]]
Average marks = 66


In [ ]:
# Task 2:
# Find highest marks in each subject

In [81]:
for i in range(len(subjects)):
    print(f"Highest marks in {subjects[i]} = {marks[:,[i]].max()}")

Highest marks in Math = 90
Highest marks in Science = 104
Highest marks in English = 100


In [ ]:
# Task 3:
# Find total marks of each student

In [80]:
for i in range(len(marks)):
    print(f"Student{i+1} Total marks = {marks[i:,].sum()}")

Student1 Total marks = 1286
Student2 Total marks = 1015
Student3 Total marks = 772
Student4 Total marks = 576
Student5 Total marks = 387
Student6 Total marks = 227


In [ ]:
# Task 4:
# Add 5 grace marks to all students

In [79]:
marks = marks + 5
print(marks)

[[ 90  81 100]
 [ 87  93  63]
 [ 76  72  48]
 [ 72  40  77]
 [ 40  72  48]
 [ 42 104  81]]


In [ ]:
#  ====================================================================
#                           MINI CHALLENGE
# =====================================================================

In [ ]:
# 👉 Combine everything

# Create dataset:

# 10 products
# price between 100–1000
# quantity between 1–20

# Do:

# ✅ total revenue
# ✅ average price
# ✅ max quantity
# ✅ increase price
# ✅ add new product
# ✅ print final dataset

In [90]:
product_id = np.arange(1,11).reshape(10,1)
product_price = np.random.randint(100, 1000,(10,1))
product_qty = np.random.randint(1,10,(10,1))

products = np.hstack((product_id,product_price,product_qty))

In [91]:
print(products)

[[  1 478   2]
 [  2 801   3]
 [  3 328   9]
 [  4 953   6]
 [  5 142   3]
 [  6 137   4]
 [  7 968   3]
 [  8 824   8]
 [  9 313   6]
 [ 10 207   2]]


In [102]:
# ✅ total revenue
total_revenue_products = products[:,1] * products[:,2]
products_total_r = total_revenue_products.sum()
print("Total Revenue =", products_total_r)

# ✅ average price
avg_price = products[:,1].mean()
print("Average price = ", avg_price)

# ✅ max quantity
max_qty = products[:,2].max()
print("Highest Quantity = ", max_qty)

# ✅ increase price
products[:,1] = products[:,1]+100
print(products[:,1])

# ✅ add new product
new_prod = np.array([[11, 300, 8]])
products = np.append(products,new_prod, axis=0)

# ✅ print final dataset
print("Final products:\n",products)

Total Revenue = 53391
Average price =  904.25
Highest Quantity =  9
[1078 1401  928 1553  742  737 1568 1424  913  807  500  400]
Final products:
 [[   1 1078    2]
 [   2 1401    3]
 [   3  928    9]
 [   4 1553    6]
 [   5  742    3]
 [   6  737    4]
 [   7 1568    3]
 [   8 1424    8]
 [   9  913    6]
 [  10  807    2]
 [  11  500    8]
 [  11  400    8]
 [  11  300    8]]
