In [ ]:
# ***********************************
#         ADVANCED NUMPY
# ***********************************

In [1]:
import numpy as np

emp = np.array([
    [1, 25000, 1],
    [2, 40000, 3],
    [3, 60000, 5],
    [4, 30000, 2],
    [5, 80000, 7]
])

In [2]:
# Columns:

# 0 → Emp_ID
# 1 → Salary
# 2 → Experience

In [3]:
# 1. Filtering
# Get employees with salary > 40000

high_salary = emp[emp[:,1] > 40000]

print(high_salary)

[[    3 60000     5]
 [    5 80000     7]]


In [6]:
# 2. Multiple Conditions
# Salary > 30000 AND Experience > 2

result = emp[(emp[:,1] > 30000) & (emp[:,2] > 2)]
print(result)

# Salary < 30000 OR Experience > 5
result2 = emp[(emp[:,1] < 30000) | (emp[:,2] > 5)]
print(result2)

[[    2 40000     3]
 [    3 60000     5]
 [    5 80000     7]]
[[    1 25000     1]
 [    5 80000     7]]


In [7]:
# 3. Boolean Indexing
condition = emp[:,1] > 50000

print(condition)

[False False  True False  True]


In [8]:
# 4. Modify Data with Condition
#  Increase salary by 5000 where salary < 30000

emp[emp[:,1] < 30000, 1] += 5000

In [9]:
# 5. np.where() (Very Important)
labels = np.where(emp[:,1] > 50000, "High", "Low")

print(labels)

['Low' 'Low' 'High' 'Low' 'High']
