In [1]:
# **************************************
#     Dataset 1 — E-commerce Orders
# **************************************

In [1]:
# columns = [Order_ID, Amount, Quantity, Discount%]

In [2]:
import numpy as np

orders = np.array([
    [1001, 5000, 2, 10],
    [1002, 2000, 1, 5],
    [1003, 8000, 4, 20],
    [1004, 1500, 1, 0],
    [1005, 6000, 3, 15],
    [1006, 3000, 2, 0]
])

In [ ]:
# Task 1 — High Value Orders
# Find orders where:
# Amount > 5000

In [4]:
high_value_orders = orders[orders[:,1]>5000]
print(high_value_orders)

[[1003 8000    4   20]
 [1005 6000    3   15]]


In [ ]:
#Task 2 — Discount Analysis
# Find orders where:
# Discount > 10%

In [6]:
high_discount = orders[orders[:,3]>10]
print(high_discount)

[[1003 8000    4   20]
 [1005 6000    3   15]]


In [ ]:
# Task 3 — Multiple Condition
# Find orders where:
# Amount > 3000 AND Quantity >= 2

In [9]:
mult_condtn = orders[(orders[:,1]>3000) & (orders[:,2]>=2)]
print(mult_condtn)

[[1001 5000    2   10]
 [1003 8000    4   20]
 [1005 6000    3   15]]


In [ ]:
# Task 4 — Apply Discoun
# Final Amount = Amount - Discount
# Modify dataset:
# Apply discount only where Discount > 0

In [13]:
# Step 1: Create condition
condition = orders[:,3] > 0

# Step 2: Apply discount
orders[condition, 1] = orders[condition, 1] - (
    orders[condition, 1] * orders[condition, 3] / 100
)

print(orders)

[[1001 4500    2   10]
 [1002 1900    1    5]
 [1003 6400    4   20]
 [1004 1500    1    0]
 [1005 5100    3   15]
 [1006 3000    2    0]]


In [14]:
# Task 5 — Label Orders
# Create labels:
# "High" if Amount > 5000
# "Low" otherwise

In [15]:
labels = np.where(orders[:,1]>5000, "High", "Low")
print(labels)

['Low' 'Low' 'High' 'Low' 'High' 'Low']


In [ ]:
# ****************************************
#     Dataset 2 — Employee Performance
# ****************************************  

In [16]:
# columns = [Emp_ID, Salary, Experience, Rating]

In [17]:
emp = np.array([
    [1, 25000, 1, 3],
    [2, 50000, 4, 5],
    [3, 70000, 6, 4],
    [4, 30000, 2, 2],
    [5, 90000, 8, 5],
    [6, 45000, 3, 3]
])

In [ ]:
# Task 1 — Top Performers
# Find employees where:
# Rating >= 4

In [18]:
top_performers = emp[emp[:,3]>=4]
print(top_performers)

[[    2 50000     4     5]
 [    3 70000     6     4]
 [    5 90000     8     5]]


In [ ]:
# Task 2 — Senior High Earners
# Find employees:
# Experience > 5 AND Salary > 60000

In [19]:
high_earners = emp[(emp[:,2]>5) & (emp[:,1]>6000)]
print(high_earners)

[[    3 70000     6     4]
 [    5 90000     8     5]]


In [ ]:
# Task 3 — Salary Increment
# Increase salary by 10%:
# Only for employees with Rating >= 4

In [29]:
condition2 = emp[:,3] >= 4

emp[condition2,1] = emp[condition2,1] + (
    emp[condition2,1] * emp[condition2,3] / 100
)

print(emp)

[[    1 25000     1     3]
 [    2 52500     4     5]
 [    3 72800     6     4]
 [    4 30000     2     2]
 [    5 94500     8     5]
 [    6 45000     3     3]]


In [ ]:
# Task 4 — Create Category Column
# "Senior" → Experience > 5
# "Mid" → 3–5
# "Junior" → < 3

In [34]:
experience = emp[:,2]

category = np.where(
    experience > 5, "Senior",
    np.where(experience >= 3, "Mid", "Junior")
)

print(category)

['Junior' 'Mid' 'Senior' 'Junior' 'Senior' 'Mid']


In [35]:
# Task 5 — Replace Low Ratings
# If Rating < 3 → make it 3

ratings = emp[:,3] < 3
emp[ratings,3] = 3
print(emp)

[[    1 25000     1     3]
 [    2 52500     4     5]
 [    3 72800     6     4]
 [    4 30000     2     3]
 [    5 94500     8     5]
 [    6 45000     3     3]]


In [ ]:
# **************************************************
#     Dataset 3 — Student Result Analysis
# **************************************************

In [36]:
# [Math, Science, English]
marks = np.array([
    [78, 85, 90],
    [40, 35, 50],
    [88, 92, 95],
    [60, 65, 70],
    [30, 25, 40]
])


In [ ]:
# Task 1 — Failed Students
# Find students where:
# Any subject < 35

In [45]:
failed_students = marks[np.any(marks<35, axis=1)]
print(failed_students)

[[30 25 40]]


In [ ]:
# Task 2 — Top Students
# Find students where:
# All subjects > 80

In [47]:
top_students = marks[np.all(marks>80, axis=1)]
print(top_students)

[[88 92 95]]


In [ ]:
# Task 3 — Add Grace Marks
# Add 5 marks:
# Only to students with average < 50

In [71]:
avg = np.all(marks<marks.mean(), axis=1)
marks[avg] = marks[avg] + 5
print(marks)

[[78 85 90]
 [45 50 60]
 [88 92 95]
 [60 65 70]
 [35 40 50]]


In [ ]:
# Task 4 — Pass/Fail Label
# "Pass" → all subjects >= 35
# "Fail" → otherwise

In [72]:
result = np.where(np.all(marks>=35, axis=1), "pass", "fail")
print(result)

['pass' 'pass' 'pass' 'pass' 'pass']


In [ ]:
# Task 5 — Subject-wise Analysis
# Find max marks per subject
# Find average marks per subject

In [86]:
max_marks = np.max(marks, axis=1)
print("MAXIMUM MARKS:")
for i in range(len(max_marks)):
    print(f"Student{i+1} Maximum marks = {max_marks[i]}")
print("\n")

avg_marks = np.mean(marks, axis=1)
print("AVERAGE MARKS:")
for i in range(len(max_marks)):
    print(f"student{i+1} Average marks = {round(avg_marks[i])}")

MAXIMUM MARKS:
Student1 Maximum marks = 90
Student2 Maximum marks = 60
Student3 Maximum marks = 95
Student4 Maximum marks = 70
Student5 Maximum marks = 50


AVERAGE MARKS:
student1 Average marks = 84
student2 Average marks = 52
student3 Average marks = 92
student4 Average marks = 65
student5 Average marks = 42


In [ ]:
# ==================================
#          Mini Project
# ==================================

In [ ]:
# Create dataset:

# 10 customers
# purchase amount (1000–10000)
# visits (1-10)

# Do:

# high value customers (>5000)
# frequent customers (>5 visits)
# give discount:

# 10% if both conditions true
# label:
# "Premium" / "Regular"

In [120]:
purchase_amount = np.random.randint(1000, 10000,(10,1))
visits = np.random.randint(1,10,(10,1))

In [121]:
customers = np.hstack((purchase_amount, visits))
print("Customer details:\n", customers)

Customer details:
 [[8702    8]
 [5875    6]
 [8652    4]
 [2838    7]
 [8195    1]
 [7612    4]
 [4373    4]
 [3719    4]
 [7375    7]
 [9481    4]]


In [95]:
# high value customers (>5000)
high_value_customers = customers[customers[:,0]>5000]
print("High Value customers: \n", high_value_customers)

High Value customers: 
 [[8033    8]
 [9025    5]
 [9781    4]
 [6889    6]
 [8593    5]
 [9753    4]
 [8462    1]
 [7256    4]]


In [122]:
# frequent customers (>5 visits)customers[customers[:,1]>5]
frequent_customers = customers[customers[:,1]>5]
print(frequent_customers)

[[8702    8]
 [5875    6]
 [2838    7]
 [7375    7]]


In [ ]:
# give discount:
# 10% if both conditions true

discount_cndtn1 = customers[:,0]>5000
discount_cndtn2 = customers[:,1]>5
discount_cndtn = discount_cndtn1 & discount_cndtn2

customers[discount_cndtn, 0] = customers[discount_cndtn, 0] - (customers[discount_cndtn, 0] * 10/100)
print("After Discount: \n:", customers)



After Discount: 
: [[6342    8]
 [4758    6]
 [8652    4]
 [2838    7]
 [8195    1]
 [7612    4]
 [4373    4]
 [3719    4]
 [5375    7]
 [9481    4]]


In [148]:
# "Premium" / "Regular"
customer_type = np.where(discount_cndtn, "Premium", "Regular")
print(customer_type)

['Premium' 'Regular' 'Regular' 'Regular' 'Regular' 'Regular' 'Regular'
 'Regular' 'Premium' 'Regular']
